# Generated by Django 4.0 on 2021-12-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='developer',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
