# Generated by Django 4.0 on 2021-12-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_actual_design_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_design',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_development',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_testing',
            field=models.IntegerField(default=0),
        ),
    ]
